FROM ruby:3.2.2-alpine

RUN apk add --no-cache \
    build-base \
    postgresql-dev \
    tzdata \
    git

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 4 --retry 3

COPY . .

RUN mkdir -p tmp/pids log

CMD ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
