default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: candidate_assessment_development

test:
  <<: *default
  database: candidate_assessment_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
